### ISSUE TITLE
Use BitlBee master instead of latest stable

### ISSUE THREAD

**Issue by realies** [stevesbrain/bitlbee-docker#12]
Plugins are basically latest master, shouldn't BitlBee be that as well?

**Comment by stevesbrain** [comment]
Only issue I would be considering with that would be if those plugins are being developed against stable version of BitlBee, or if they're being developed against BitlBee master. Happy to test it out and see, but possibly another option would be to maintain two tags in Docker hub - one for "master" and one for "stable". Thoughts?

**Comment by realies** [comment]
Agreed. All plugins seem to have stable releases that can be used for the `stable` tag.

**Comment by stevesbrain** [comment]
Sounds reasonable then - if you're in agreement, we'll switch to a master branches + latest docker tag as one stream, with stable BitlBee + release branches of plugins with stable docker tag as the other stream?

**Comment by stevesbrain** [comment]
Thanks for prepping the branches :) I'll do the actual build + tests tomorrow, then push up to hub from there.

**Comment by stevesbrain** [comment]
Tested both, worked for me :) Have pushed to docker hub now (FB is slower on stable branch though - presuming this is due to changes they've introduced in the meantime).
