### ISSUE TITLE
Improve repository metadata

### ISSUE THREAD

**Issue by realies** [stevesbrain/bitlbee-docker#16]
Suggesting that the GitHub repository description changes to something like `🐳 BitlBee on Alpine with Plugins Docker Container` with the addition of the topics `bitlbee, alpine, plugins, irc, instant messaging, im, gateway, discord, facebook, skype, steam, telegram`.

**Comment by stevesbrain** [comment]
Agreed, and done :) Thanks!

**Comment by realies** [comment]
Perhaps have `https://hub.docker.com/r/vanityshed/bitlbee-alpine-plugins/` in the repository website field too? So just the Docker hub and the Github repo are linked both ways... :o)

**Comment by stevesbrain** [comment]
Good call; and done :)
