### ISSUE TITLE
Feature Request: LINE integration

### ISSUE THREAD

**Issue by brianclemens** [stevesbrain/bitlbee-docker#18]
bitlbee supports LINE via the [libpurple plugin](http://altrepo.eu/git/line-protocol)

**Comment by realies** [comment]
@brianclemens, since not a user of LINE, would you be able to assist with testing? Can see that the last activity on the linked repository is from one year ago with the last commit from three years ago. That makes me think the project is not active as the protocol is likely to have changed since then.

**Comment by brianclemens** [comment]
@realies I sure would!  I tried to get it in the image myself.  Found a blurb [here](https://gist.githubusercontent.com/shiroyasha/c6880588d57c109ffc2fbb52c4bad663/raw/3073b359066d87198cb668e81fa504612f258c93/alpine-install-thrift) to get thrift installed, got the plugin compiled and in the right places, but couldn't get it to show up in the `help purple` list

**Comment by realies** [comment]
Where do you attempt the `help purple` command? Bitlbee lists enabled external plugins and protocols with the `plugins` command within a control channel.

**Comment by brianclemens** [comment]
@realies Line doesn't show in either of those commands from the &bitlbee channel.
![2018-04-04-135319_1232x1347_scrot](https://user-images.githubusercontent.com/13581364/38289119-8e0d7694-380f-11e8-8142-0f0515ad1f93.png)

**Comment by brianclemens** [comment]
Added in my fork.

**Comment by realies** [comment]
Last working on this I was attempting to compile thrift from source under alpine, which was not as straight-forward. Updating the the dead link in the `purple-line` does seem to make it work, but it is still using an outdated version of thrift (https://github.com/apache/thrift/releases). Considering `purple-line` is not active for some time now, this might not be relevant. Mind a pull request?
