### ISSUE TITLE
Couldn't write PID

### ISSUE THREAD

**Issue by realies** [stevesbrain/bitlbee-docker#2]
Running the container with `docker run -d --name=bitlbee -v /mnt/user/appdata/bitlbee:/bitlbee-data:rw -p 6667:6667 vanityshed/bitlbee-alpine-plugins` results in `Warning: Couldn't write PID to '/var/run/bitlbee.pid'`. Changing the permissions and owner of the `/var/run` folder does not resolve  it. 

Edit: However, everything seems to be working fine no matter the warning.

**Comment by stevesbrain** [comment]
Thanks for reporting @realies - I am running this in production too, so can confirm all seems to be working fine. I'll check out the warning though and see if I can reproduce + work on a fix :)

**Comment by stevesbrain** [comment]
@realies This should be solved in latest commit - solves it for my system at least, so I imagine for yours too. Let me know if this isn't solved for you (currently building as latest on Docker hub, and should be done in 10 minutes or so).
