### ISSUE TITLE
Multi-stage build

### ISSUE THREAD

**Issue by vbrandl** [stevesbrain/bitlbee-docker#23]
While the resulting image is already pretty small, using a multi-stage build might result in yet a smaller image. The build image should install all the `*-dev` dependencies but the runtime image doesn't need the `dev` dependencies. Earlier today I created a small bitlbee Docker image myself that does not add any plugins but is only 17 MB.

I guess your image would benefit from this as well.

```Dockerfile
FROM alpine:3.7 as builder
WORKDIR /usr/src/app
RUN apk add --no-cache wget glib-dev gnutls-dev python build-base libgcrypt-dev libotr-dev
ENV VERSION 3.5.1
RUN wget https://github.com/bitlbee/bitlbee/archive/$VERSION.tar.gz
RUN tar xf $VERSION.tar.gz
WORKDIR /usr/src/app/bitlbee-$VERSION
RUN ./configure --debug=0 --prefix=/usr --etcdir=/etc/bitlbee --otr=1
RUN make

FROM alpine:3.7
RUN apk add --no-cache glib gnutls libgcrypt libotr
COPY --from=builder /usr/src/app/bitlbee-3.5.1/bitlbee /bin/
EXPOSE 6667
# CMD ["/bin/bitlbee", "-n", "-c", "/etc/bitlbee/bitlbee.conf"]
CMD ["/bin/bitlbee", "-n"]
```

**Comment by realies** [comment]
We separate build from runtime dependencies and clean the image at the end of the build. This is what happens for `json-glib-dev` and `json-glib`. It is reasonable to follow the pattern for the remaining packages for consistency and to maintain the image minimal. Feel free to follow this up with a PR.

**Comment by stevesbrain** [comment]
Thanks @vbrandl - as @realies said, we're currently doing a clean via multi-line build (so new snapshots are not taken at each stage) rather than via multi-stage build.

I do however like the readability of the multi-stage build. Can you confirm if the multi-stage comes out to be smaller than the equivalent multi-line? If not, I can happily test.

**Comment by vbrandl** [comment]
I'm even thinking of building each plugin in an own stage so when updating the commit hash for a plugin only the plugin will be rebuilt.
Depending on how complex the `make install` steps are, this might be rather complicated to do. I'll look into it.

**Comment by stevesbrain** [comment]
Thanks @vbrandl - looking forward to testing out #24 soon :) Appreciate the work you've put in!

**Comment by realies** [comment]
Closing via #26

**Comment by stevesbrain** [comment]
Thanks @realies and @vbrandl :)
