### ISSUE TITLE
Add support for Telegram

### ISSUE THREAD

**Issue by realies** [stevesbrain/bitlbee-docker#3]
Would it be possible to integrate [telegram-purple](https://github.com/majn/telegram-purple)?

**Comment by stevesbrain** [comment]
@realies I'll begin to have a look into getting this happening :)

**Comment by stevesbrain** [comment]
FYI @realies I've started working on it in 8637748 - however, it is not yet working, so I haven't pushed to master. The compile script for this isn't picking up Alpine's libpurple, so I've gotta work on either getting that happening, or installing my own manually.

Failing that, I'll branch off and do a Debian based package for you instead which includes everything (though will be a slightly larger image). I may or may not have more time to work on this tomorrow, but if not, definitely on Tuesday :)

**Comment by realies** [comment]
@stevesbrain, #4 should do.

**Comment by stevesbrain** [comment]
Appreciate it @realies - final close for this issue in commit 3b3ba21  - building on docker hub now :)
