### ISSUE TITLE
Add support for Skype

### ISSUE THREAD

**Issue by realies** [stevesbrain/bitlbee-docker#7]
Would be great to have Skype as an option to the BitlBee protocols. It seems [skype4pidgin](https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb) is the most recent solution.

**Comment by stevesbrain** [comment]
Will start to give a look at this in a few days - thanks :)

**Comment by realies** [comment]
#8 should suffice. Perhaps the readme needs an update as well.

**Comment by stevesbrain** [comment]
Closing this now that it's been merged. Will get a readme update happening :)
